name: Build and Push Docker Image
on:
  push:
    branches:
      - master # Chỉ chạy workflow khi có thay đổi trên nhánh main (có thể thay đổi theo nhu cầu)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Bước checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước đăng nhập DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Bước build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-image-name:latest .

    # Bước push Docker image lên DockerHub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-image-name:latest
